name: esm-v4
channels:
  - nvidia
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=12.4
  - python=3.11
  - pytorch
  - torchvision
  - biopython
  - pandas
  - jupyterlab
  - scipy
  - tqdm
  - matplotlib
  - ete3
  - ipykernel
  - scikit-learn
  - numpy[version='<2']
  - seaborn
  - pyfaidx
