_target_: src.loss.hier_supcon.hierSupConLoss
temperature: 0.5
correlation_dir: /gpfs/commons/home/nkeung/Contrastive_Learning/data/phylo_dist
# correlation_dir: /mnt/home/nlk2136/Contrastive_Learning/data/phylo_dist
weight_mode: adaptive