seq_len: 199    
data_file: "/mnt/home/at3836/Contrastive_Learning/data/final_data/intronSeq_multizAlignment_noDash/merged_intron_sequences.pkl"
exon_names_path: "/mnt/home/at3836/Contrastive_Learning/data/final_data/intronSeq_multizAlignment_noDash/all_exon_names.txt"
batch_size_per_device: ${div_up:${task.global_batch_size}, ${eval:${trainer.devices}  * ${trainer.num_nodes}}} 
# num_workers: 1          # Number of workers for data loading
num_workers: ${optimal_workers:}
train_ratio: 0.8       # Train split ratio
val_ratio:  0.1
test_ratio: null      # Evaluation split ratio
cache_dir: "../data"         # Cache directory for the dataset
