_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": lr-SGD
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
                - 71
                - 106
            "2":
                - 1
                - 11
                - 41
                - 49
                - 50
                - 55
                - 71
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.10.15
            "5": 0.18.7
            "6": 4.46.2
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
aux_models:
    value:
        freeze_encoder: false
        hidden_dim: 512
        name_or_path: psi_regression
        output_dim: 1
        warm_start: true
callbacks:
    value:
        learning_rate_monitor:
            _target_: lightning.pytorch.callbacks.LearningRateMonitor
            logging_interval: step
        model_checkpoint:
            _target_: lightning.pytorch.callbacks.ModelCheckpoint
            dirpath: checkpoints/
            filename: psi_regression/TISFM/201/best-checkpoint
            mode: min
            monitor: val_loss
            save_last: true
            save_top_k: 1
            verbose: true
dataset:
    value:
        batch_size_per_device: 2048
        cache_dir: ../data
        num_workers: 16
        seq_len: 201
        test_file: /mnt/home/at3836/Contrastive_Learning/data/final_data/ASCOT_finetuning/psi_variable_Retina___Eye_psiWmean_intron_sequences_dict.pkl
        train_file: /mnt/home/at3836/Contrastive_Learning/data/final_data/ASCOT_finetuning/psi_train_Retina___Eye_psi_intron_sequences_dict.pkl
        val_file: /mnt/home/at3836/Contrastive_Learning/data/final_data/ASCOT_finetuning/psi_val_Retina___Eye_psi_intron_sequences_dict.pkl
embedder:
    value:
        _name_: TISFM
        maxpooling: true
        motif_path: /mnt/home/at3836/Contrastive_Learning/data/motifs/cisBP_mouse.meme
        name_or_path: TISFM
        num_of_response: 1
        pad_motif: 4
        seq_len: 200
        stride: 1
logger:
    value:
        _target_: lightning.pytorch.loggers.WandbLogger
        group: psi_regression
        id: psi_regression-Psi__20250519_220832
        log_model: true
        name: Psi__20250519_220832
        notes: Anshul data tisfm
        project: PSI_REGRESSION
        save_dir: ./wandb/
        settings:
            init_timeout: 600
loss:
    value:
        _target_: torch.nn.MSELoss
model:
    value:
        hidden_dim: 512
        name_or_path: simclr
        projection_dim: 128
optimizer:
    value:
        _target_: torch.optim.SGD
        lr: 0.001
        momentum: 0.9
        weight_decay: 0
task:
    value:
        _name_: psi_regression
        global_batch_size: 2048
        metrics:
            - r2_score
        pretraining_weights: exprmnt_2025_05_19__21_23_02
        val_check_interval: 0.5
tokenizer:
    value:
        _target_: src.tokenizers.onehot_tokenizer.FastOneHotPreprocessor
        padding: right
        seq_len: 200
trainer:
    value:
        _target_: lightning.pytorch.Trainer
        accumulate_grad_batches: 1
        callbacks: null
        devices: 1
        gradient_clip_val: 1
        limit_train_batches: 1
        limit_val_batches: 1
        log_every_n_steps: 1
        max_epochs: 30
        num_nodes: 1
        num_sanity_val_steps: 0
        precision: 16-mixed
        val_check_interval: 0.5
wandb:
    value:
        api_key: 6c6c3f0e63c48c1d9b78f03948c5eb5a4f828a66
        dir: ./wandb/
