defaults:
  - _self_
  - embedder: ntv2
  - dataset: psi_dataset  # Custom dataset for PSI regression
  - task: psi_regression_task
  - trainer: default_trainer
  - callbacks: default_callbacks
  - tokenizer: custom_tokenizer
  - loss: mse_loss
  - model: psi_regression_model
  - optimizer: adamw

hydra:
  run:
    dir: ./hydra/psi_regression/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: false

wandb:
  api_key: "6c6c3f0e63c48c1d9b78f03948c5eb5a4f828a66"
  dir: ./wandb/psi_regression
  settings:
    init_timeout: 600  # Increase timeout to 10 minutes

logger:
  _target_: lightning.pytorch.loggers.WandbLogger
  name: PSI-${dataset.seq_len}
  id: ${task._name_}-${.name}
  project: PSI_REGRESSION
  group: ${task._name_}
