_name_: psi_regression
metrics:
  - r2_score  # R² score for regression evaluation
  - mse       # Mean Squared Error (MSE) as loss
val_check_interval: 64  # Adjusted validation frequency
global_batch_size: 256  # Increased batch size for better memory utilization
